### PR TITLE
File Setup

### LINKED ISSUE #3: Add README template
- [x] Add contributors
- [x] Add BE repo link

### LINKED ISSUE #18: Define CSS Variables
See [Figma comp](https://www.figma.com/design/NMuE9LguXNCmSYXSVotx80/Brain-Defrost?node-id=0%3A1&t=OnNfUQi77Fa5jBH9-1) for colors and fonts

### Define global styles
- [x] border-box sizing
- [x] heading and text style rules (font, size, weight, etc)
- [x] color palette variables
- [x] drop-shadow & other filters

### LINKED ISSUE #20: File Setup
- [ ] Install `socket.io`
- [ ] Create `socket.ts` file in `src` directory
- [x] Create `components` folder in `src` directory
- [x] Create folders with `css` and `tsx` files for each component
- [x] Install React Router

### PR DESCRIPTION
**Pull request by tednaphil**
# Brain Defrost FE

## Summary 
- Creation of `component` folder and files for components + import of `css` files and `export default` statements for each `tsx` component file 
- Installation of React Router and import of `BrowserRouter` to `index.tsx` component closes #20 
- Definition of preliminary CSS variables based on mockup closes #18 
- Addition of `README` template and initial content (e.g. contributor names) closes #3 

## Changes Made
- Updated favicon
- Added `images` directory to the `src` directory

## Checklist
- [x] The code follows the project's coding standards.
- [ ] Unit tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes (if applicable).
- [x] The code compiles without errors.
- [x] All new and existing tests pass.
- [ ] The pull request has been reviewed by at least one other contributor.

## Additional Information/Next Steps
- Held off on installing `socket.io` or `socket.io client` until we do more research to decide which API we'll start with
- Some of the initial `create react app` content remains in the repo (namely in the `App.css` file) - please remove any of those rules as needed!

### CODE REVIEW

**Review by EthanDuvall — APPROVED** [review]
Thats great ill merge but i think we should also add a interface and fetch calls folder

**Comment by EthanDuvall** [comment]
Errr i cant merge tayla This is the error "Merging is blocked
Missing successful active github-pages deployment." and im thinking i wait to merge cuz im not sure if we want to change to rules or unskip those checks !

**Comment by tednaphil** [comment]
The preview deployment is showing successful (see below), but the preview link is not being provided like the action's docs said it would be. Additionally, the link that is shown in the job console shows a 404 page, so it's safe to say it's not working as intended, so I've commented it out for now 😅.

Merging will require a successful running of tests to merge. Once successfully tests changes are merged to `main`, the successful build will be deployed to `ghpages`.

Screenshot 2024-05-11 at 8 39 27 AM

**Review by EthanDuvall — APPROVED** [review]
Thank you for adding those files

**Pull request merged**
